apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-app
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
        - name: wordpress
          image: wordpress-docker
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - chmod +x /check.sh && ./check.sh
            initialDelaySeconds: 15
            periodSeconds: 10
          ports:
            - containerPort: 80
      restartPolicy: Always
