apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps-app
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      containers:
        - image: ftps-docker
          name: ftps
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - chmod +x /check.sh && ./check.sh
            initialDelaySeconds: 15
            periodSeconds: 10
          ports:
            - containerPort: 21
              name: ftps-0
            - containerPort: 30030
              name: ftps-1
      restartPolicy: Always
