apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana-app
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
        - name: grafana
          image: grafana-docker
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - chmod +x /check.sh && ./check.sh
            initialDelaySeconds: 15
            periodSeconds: 10
          ports:
            - containerPort: 3000
      restartPolicy: Always
