apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-influx
  labels:
    task: influx
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/influx/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-influx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      task: influx
