apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  selector:
    app: ftps-app
  ports:
    - port: 21
      targetPort: 21
      name: ftps-0
    - port: 30030
      targetPort: 30030
      name: ftps-1
  type: LoadBalancer
