apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  selector:
    app: grafana-app
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
