apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  selector:
    app: wordpress-app
  ports:
    - port: 5050
      targetPort: 80
  type: LoadBalancer
