apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  selector:
    app: phpmyadmin-app
  ports:
    - port: 5000
      targetPort: 80
  type: LoadBalancer
