apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  selector:
    app: nginx-app
  ports:
    - port: 80
      name: port1
      targetPort: 80
    - port: 443
      name: port2
      targetPort: 443
    - port: 23
      name: ssh
      targetPort: 22
  type: LoadBalancer
