apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana-app
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
        - name: grafana
          image: grafana-docker
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
