apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql-docker
          name: mysql
          imagePullPolicy: Never
          #   env:
          #     # Use secret in real usage
          #   - name: MYSQL_ROOT_PASSWORD
          #     value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
#reference:
#   persistent volume:https://medium.com/@ngugijoan/persistent-volume-and-persistent-volume-claims-kubernetes-8ded0eb1cd6a
