apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps-app
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      containers:
        - image: ftps-docker
          name: ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 21
              name: ftps-0
            - containerPort: 30030
              name: ftps-1
#          volumeMounts:
#            - mountPath: "/home/abdelali"
#              name: ftp-persistent-storage
#      volumes:
#        - name: ftp-persistent-storage
#          persistentVolumeClaim:
#            claimName: pvc-ftp
