apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  labels:
    app: ftps
spec:
  selector:
    app: ftps-app
  ports:
    - port: 21
      targetPort: 21
      name: ftps-0
      #nodePort: 30010
    - port: 30030
      targetPort: 30030
      #nodePort: 30030
      name: ftps-1
  type: LoadBalancer
